print('hello world')
print('hello again')
print('i like typing this')
print('this is fun')
print('yah printing')
print('I lost')
print('heavens whore')
print('I love vodka')
print('killing in the name')
print('make yourself better')