Name = input('Whats your name?  ')
From = input('Where are you from?  ')
Uni = input('Where are you read in?  ')
Semester = input('Which semester are you read in?  ')
Interest = input('In which sector you are interested?  ')
Language = input('In which language you are working?  ')
Framework = input('Hopefully you will working with?  ')